name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
      - ldennington/fix-winget-action

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        ref: ldennington/fix-winget-action
    - name: Update winget repository
      uses: ./
      with:
        id: Microsoft.GitCredentialManagerCore
        version: 2.0.194.40577
        token: ${{ secrets.WINGET_TOKEN }}
        manifestText: 'PackageIdentifier: Microsoft.GitCredentialManagerCore'
        alwaysUsePullRequest: true
