name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
      - ldennington/fix-winget-action

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ldennington/fix-winget-action
      - run: |
          npm install
      - run: |
          npm run build
      - name: Update winget repository
        uses: ./
        with:
          id: Microsoft.GitCredentialManagerCore
          version: 2.0.194.40577
          token: ${{ secrets.WINGET_TOKEN }}
          manifestText: 'PackageIdentifier: Microsoft.GitCredentialManagerCore'
          alwaysUsePullRequest: true
          releaseRepo: 'microsoft/Git-Credential-Manager-Core'
          releaseTag: 'v2.0.194-beta'
