name: 'build-test'
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: update-winget
        name: Update winget repository
        uses: mjcheetham/update-winget@v1.3.2

        with:
          id: Microsoft.Git
          token: ${{ secrets.WINGET_TOKEN }}
          releaseAsset: Git-([0-9.vfs]*)\-64-bit.exe
          releaseRepo: microsoft/git
          repo: ldennington/winget-playground
          releaseTag: v2.32.0.vfs.0.0
          manifestText: |
            PackageIdentifier: {{id}}
            PackageVersion: {{version:s/\.[A-Za-z]+\././}}
            PackageName: Microsoft Git
            Publisher: The Git Client Team at GitHub
            Moniker: microsoft-git
            PackageUrl: https://aka.ms/ms-git
            Tags: [ microsoft-git ]
            License: GPLv2
            ShortDescription: |
              Git distribution to support monorepo scenarios.
              Note: This is not Git for Windows. Unless you are working in a monorepo and require
              specific Git modifications, please run `winget install git` to start using Git for Windows.
            Installers:
            - Architecture: x64
              InstallerUrl: {{url}}
              InstallerType: inno
              InstallerSha256: {{sha256}}
            PackageLocale: en-US
            ManifestType: singleton
            ManifestVersion: 1.0.0
        alwaysUsePullRequest: true