name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
      - ldennington/fix-winget-action

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Update winget repository
      uses: ./
      with:
        id: Microsoft.GitCredentialManagerCore
        version: 2.0.194.40577
        token: ${{ secrets.WINGET_TOKEN }}
        manifestText: |
          PackageIdentifier: Microsoft.GitCredentialManagerCore
          PackageVersion: 2.0.194.40577
          PackageName: Git Credential Manager Core
          Publisher: Microsoft Corporation
          Moniker: git-credential-manager-core
          PackageUrl: https://aka.ms/gcmcore
          License: Copyright (C) Microsoft Corporation
          ShortDescription: Secure, cross-platform Git credential storage with authentication to GitHub, Azure Repos, and other popular Git hosting services.
          Installers:
          - Architecture: x64
            InstallerUrl: https://github.com/microsoft/Git-Credential-Manager-Core/releases/download/v2.0.194-beta/gcmcore-win-x86-2.0.194.40577.exe
            InstallerType: inno
            InstallerSha256: 26D3662F66E6AEC76C3BF155028D22D30ED8D1F1AFFA7C676F8DB0426939E8AD
          PackageLocale: en-US
          ManifestType: singleton
          ManifestVersion: 1.0.0
        alwaysUsePullRequest: true
